version: "3"
services:
  
  master:
    container_name: master
    build: YACS/master/.
    ports:
      - 5000
      - 5001
    depends_on:
      - postgres
 
  worker1:
    container_name: worker1
    build: YACS/worker/.
    ports: 
      - 4000
    depends_on: 
      - master

